on:
  push:
    paths:
      - '.github/workflows/ffmpeg.yml'
  schedule:
    - cron: '0 20 * * 2'
  workflow_dispatch:

name: ffmpeg
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup variables
        id: setup_variables
        run: |
          echo "FFMPEG=$(wget -qO- https://api.github.com/repos/BtbN/FFmpeg-Builds/tags | grep 'name' | cut -d\" -f4 | head -1)" >> $GITHUB_OUTPUT
          echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
          echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Start build
        run: |
          # For uncompress xz format 
          sudo apt-get install -y xz-utils
          # Build windows 64 bit GPL
          mkdir -p ffmpeg-windows
          pushd ffmpeg-windows || exit 1
          wget -qO- https://api.github.com/repos/GyanD/codexffmpeg/releases/tags/$(echo $(wget -qO- https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z.ver))  | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | grep -E ".*full_build.7z" | wget -O ffmpeg-windows.7z -i -
          7z x ffmpeg-windows.7z && rm -rfv ffmpeg-windows.7z
          mv ffmpeg-*/bin/*.exe .
          rm -rfv ffmpeg-*
          7z a -mx=9 -mfb=64 -md=128m ffmpeg-windows.7z ff*.exe
          popd || exit 1
          # Build linux 64 bit GPL git
          mkdir -p ffmpeg-linux
          pushd ffmpeg-linux || exit 1
          wget -qO- https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/tags/${{ steps.setup_variables.outputs.FFMPEG }} | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | grep -E ".ffmpeg-.*-linux64-gpl.tar.xz" | sort -r | head -1 | wget -O ffmpeg-linux.tar.xz -i -
          tar -xJf ffmpeg-linux.tar.xz && rm -rfv ffmpeg-linux.tar.xz
          mv ffmpeg-*/bin/* .
          rm -rfv ffmpeg-*
          7z a -mx=9 -mfb=64 -md=128m ffmpeg-linux.7z ff*
          popd || exit 1
          # Build linux 64 bit GPL Release
          mkdir -p ffmpeg-linux-release
          pushd ffmpeg-linux-release || exit 1
          wget -O ffmpeg-linux-release.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xJf ffmpeg-linux-release.tar.xz && rm -rfv ffmpeg-linux-release.tar.xz
          mv ffmpeg-*/ff* .
          rm -rfv ffmpeg-*
          7z a -mx=9 -mfb=64 -md=128m ffmpeg-linux-release.7z ff*
          popd || exit 1
          mkdir -p release
          pushd release || exit 1
          cp -r ../ffmpeg-windows/*.7z .
          cp -r ../ffmpeg-linux/*.7z .
          cp -r ../ffmpeg-linux-release/*.7z .
          popd || exit 1

      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: FFmpeg ${{ steps.setup_variables.outputs.DATE }}
          tag: ${{ steps.setup_variables.outputs.VERSION }}
          draft: false
          prerelease: false
          artifacts: |
            ./release/*.7z

      - name: Delete Older Release
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          repo: youcmd/ffmpegbuildlinux
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
