on:
  push:
    paths:
      - '.github/workflows/ffmpeg.yml'
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:

name: ffmpeg
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup variables
        run: |
          echo "FFMPEG=$(wget -qO- https://api.github.com/repos/BtbN/FFmpeg-Builds/tags | grep 'name' | cut -d\" -f4 | head -1)" >> $GITHUB_ENV
          echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
        shell: bash
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Start build
        run: |
          # For uncompress xz format 
          sudo apt-get install -y xz-utils
          # Build linux 64 bit GPL
          mkdir -p ffmpeg-linux
          pushd ffmpeg-linux || exit 1
          wget -qO- https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/tags/${{ env.FFMPEG }} | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | grep -E ".ffmpeg-.*-linux64-gpl.tar.xz" | sort -r | head -1 | wget -O ffmpeg-linux.tar.xz -i -
          tar -xJf ffmpeg-linux.tar.xz && rm -rfv ffmpeg-linux.tar.xz
          mv ffmpeg-*/bin/* .
          rm -rfv ffmpeg-*
          7z a -mx=9 -mfb=64 -md=128m ffmpeg-linux.7z ff*
          popd || exit 1
          mkdir -p release
          pushd release || exit 1
          cp -r ../ffmpeg-linux/*.7z .
          popd || exit 1

      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: FFmpeg ${{ env.DATE }}
          tag: ${{ env.VERSION }}
          draft: false
          prerelease: false
          artifacts: |
            ./release/*.7z

      - name: Delete Older Release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: youcmd/ffmpegbuildlinux
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
